#!/bin/bash

#this script opens up different quick reference material and 
# cheat sheets related to commandline 

help()
{
	echo "HELP:"
        echo "1) vi, vim"
        echo "2) doc, docker"
        echo "3) bash"
}

if [ "$#" -gt "1" ]; then
	echo "Invalid number of arguments ($#)."
	exit
fi

if [ "$#" -eq "0" ]; then
	help
	exit
fi

case $1 in 
	h|help)
		help
		;;
	#vim
	vi|vim)
		gio open ./cheat_sheets/vim.pdf
		exit
		;;
	#docker
	doc|docker)
		gio open ./cheat_sheets/docker_cheatsheet.pdf
		exit
		;;
	#bash
	bash)
		gio open ./cheat_sheets/bash_cheatsheet.pdf
		exit
		;;
	*)
		echo "Sorry, no entry for: $1." 



esac
